stages:
  - build

test:
  tags:
    - ovh
    - ifi
    - server
  image: node:8
  stage: build
  before_script:
    - apt-get update -qy
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$OVH_RUNNER_SSH_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script: # Le projet est transféré directement à la racine de ce nouveau conteneur
    - npm install
    - npm run build:preprod
    # On clean tout avant de remettre les sources
    #- ssh debian@$TEST_APP_IP 'docker ps -a | grep "haydgoki/app" | cut -d' ' -f1 | xargs -r docker stop && docker ps -a | grep "haydgoki/app" | cut -d' ' -f1 | xargs -r docker rm && rm -rf app'
    - ssh debian@$TEST_APP_IP 'docker ps -a -q --filter name="app" | xargs -r docker stop && docker ps -a -q --filter name="app" | xargs -r docker rm  && rm -rf app'
    - scp -r ./ debian@$TEST_APP_IP:app
    - ssh debian@$TEST_APP_IP 'cd app && docker build -t haydgoki/app:1.0 . && docker run -d -p 3000:3000 --name app -e ENVIRONNEMENT=preprod haydgoki/app:1.0 npm run start:preprod'
