# image: docker:latest
# services:
#   - docker:dind

# stages:
#   - build

# variables:
#   TEST_IMAGE: image_test:$CI_COMMIT_REF_NAME

# build:
#   stage: build
#   tags:
#     - docker
#     - ifi
#   script:
#     - docker info
#     # - docker build --pull -t $TEST_IMAGE .
#     # - docker push $TEST_IMAGE

#   only:
#     - dev

stages:
  - build

test:
  image: node:8
  stage: build
  tags:
    - shared
  script:
    - npm install
    - npm run build:preprod
    - ls
